version: "3.9"
services:
    api:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/workspace
        depends_on:
            - redis
        environment:
            - BASE_URL
            - EMAIL_SENDER_ADDRESS
            - EMAIL_SENDER_PASSWORD
            - EMAIL_SENDER_HOST
            - DISCLAIMER
        command: gunicorn -w 2 -b 0.0.0.0:3000 --log-file=- 'src.main:app'
    worker:
        build: .
        volumes:
            - .:/workspace
        depends_on:
            - redis
        environment:
            - BASE_URL
            - EMAIL_SENDER_ADDRESS
            - EMAIL_SENDER_PASSWORD
            - EMAIL_SENDER_HOST
        command: rq worker --url redis://redis:6379 -c worker-settings

    redis:
        image: redis
        ports:
            - "6379:6379"