version: "3.9"
services:
    api:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/workspace
        depends_on:
            - redis
        command: flask --app src/main.py --debug run --host 0.0.0.0
    worker:
        build: .
        volumes:
            - .:/workspace
        depends_on:
            - redis
        command: python src/worker.py
    redis:
        image: redis


