name: Feature Request
description: Create a feature request for WAAS
labels: ["type/feature"]
body:
  - type: textarea
    attributes:
      label: Describe the feature you'd like to request
      description: A clear and concise description of what you want and what your use case is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: false
