import type { FastifyInstance } from 'fastify';

const stats = async (fastify: FastifyInstance) => {
  fastify.get('/options/models', async (_req, _reply) => {
    return {
      defaultModel: 'large',
      models: [
        'tiny.en',
        'tiny',
        'base.en',
        'base',
        'small.en',
        'small',
        'medium.en',
        'medium',
        'large-v1',
        'large-v2',
        'large-v3',
        'large',
      ],
    };
  });

  fastify.get('/options/languages', async (_req, _reply) => {
    return [
      'english',
      'chinese',
      'german',
      'spanish',
      'russian',
      'korean',
      'french',
      'japanese',
      'portuguese',
      'turkish',
      'polish',
      'catalan',
      'dutch',
      'arabic',
      'swedish',
      'italian',
      'indonesian',
      'hindi',
      'finnish',
      'vietnamese',
      'hebrew',
      'ukrainian',
      'greek',
      'malay',
      'czech',
      'romanian',
      'danish',
      'hungarian',
      'tamil',
      'norwegian',
      'thai',
      'urdu',
      'croatian',
      'bulgarian',
      'lithuanian',
      'latin',
      'maori',
      'malayalam',
      'welsh',
      'slovak',
      'telugu',
      'persian',
      'latvian',
      'bengali',
      'serbian',
      'azerbaijani',
      'slovenian',
      'kannada',
      'estonian',
      'macedonian',
      'breton',
      'basque',
      'icelandic',
      'armenian',
      'nepali',
      'mongolian',
      'bosnian',
      'kazakh',
      'albanian',
      'swahili',
      'galician',
      'marathi',
      'punjabi',
      'sinhala',
      'khmer',
      'shona',
      'yoruba',
      'somali',
      'afrikaans',
      'occitan',
      'georgian',
      'belarusian',
      'tajik',
      'sindhi',
      'gujarati',
      'amharic',
      'yiddish',
      'lao',
      'uzbek',
      'faroese',
      'haitian creole',
      'pashto',
      'turkmen',
      'nynorsk',
      'maltese',
      'sanskrit',
      'luxembourgish',
      'myanmar',
      'tibetan',
      'tagalog',
      'malagasy',
      'assamese',
      'tatar',
      'hawaiian',
      'lingala',
      'hausa',
      'bashkir',
      'javanese',
      'sundanese',
      'cantonese',
    ];
  });
};

export default stats;
